# fly.toml app configuration file generated for showoff on 2023-09-24T18:09:05+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "showoff"
primary_region = "den"
kill_signal = "SIGTERM"
kill_timeout = 5
swap_size_mb = 512

[build]

# we don't use the migrate step because it won't mount the
# volume with our sqlite database
#[deploy]
#  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "showoff.fly.dev"
  PORT = "4000"

[http_service]
  internal_port = 4000
  force_https = true
  auto_stop_machines = false
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000

[mounts]
  source = "litefs"
  destination = "/var/lib/litefs"
