name: Elixir CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  MIX_ENV: test

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up Elixir
      uses: erlef/setup-beam@v1.20.4
      with:
        elixir-version: '1.18.4' # Define the elixir version [required]
        otp-version: '28.0.2' # Define the OTP version [required]
    - name: Restore dependencies cache
      uses: actions/cache@v4
      with:
        path: deps
        key: ${{ runner.os }}-mix-${{ hashFiles('**/mix.lock') }}
        restore-keys: ${{ runner.os }}-mix-
    - name: Install dependencies
      run: mix deps.get
    - name: Start NATS server
      run: |
        curl -L https://github.com/nats-io/nats-server/releases/download/v2.10.20/nats-server-v2.10.20-linux-amd64.tar.gz | tar -xz
        ./nats-server-v2.10.20-linux-amd64/nats-server &
    - name: Run tests
      run: mix test
    - name: Check Formatting
      run: mix format --check-formatted